#!/usr/bin/env bash

# Prompt style most of the code grabed from https://github.com/mathiasbynens/dotfiles
# Colors adjusted to Gruvbox color pallete https://github.com/morhetz/gruvbox-contrib/blob/master/color.table

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 234);
	blue=$(tput setaf 109);
	cyan=$(tput setaf 72);
	green=$(tput setaf 64);
	orange=$(tput setaf 208);
	purple=$(tput setaf 175);
	red=$(tput setaf 167);
	violet=$(tput setaf 108);
	white=$(tput setaf 223);
	yellow=$(tput setaf 214);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Using stock git-prompt script which has been shiped with
# git source code


source $HOME/.bashrc.d/git-prompt
# PROMPT_DIRTRIM=2
GIT_PS1_SHOWDIRTYSTATE=1;
GIT_PS1_SHOWUNTRACKEDFILES=1;
GIT_PS1_SHOWCOLORHINTS=1;
GIT_PS1_SHWSTASHSTATE=1;

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
    userStyle="${bold}${red}";
    promptChar="#";
else
    userStyle="${orange}";
    #promptChar="==〉";
    promptChar="$"
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
    hostStyle="${bold}${red}";
else
    hostStyle="${yellow}";
fi;

case $TERM in
    xterm*|gnome-*|screen*|xrvt*|mlterm*|tmux*)
	TITLE_BAR="\[\033]0;\w\007\]";;
    *)
	TITLE_BAR="";;
esac
if [[ -n "${VIRTUAL_ENV}" ]]; then
    virtualEnvName=$(basename $VIRTUAL_ENV);
    virtualEnvPS="${bold}${violet}[${reset}${violet}workon: ${reset}${bold}${violet}${virtualEnvName}]";
    echo $virtualEnvPS;
else
    virtualEnvPS="";
    echo $virtualEnvPS;
fi

# PROMPT_COMMAND= 'gitPromptCommand'

PROMPT_COMMAND='__git_ps1 \
"$TITLE_BAR\[${bold}\]\n\[${reset}\]\[${userStyle}\]\u \
\[${white}\]@ \[${hostStyle}\]\h \[${white}\]: \[${cyan}\]\w \
\[${reset}\]" "\n\[${white}\]$promptChar \[${reset}\]"';

export PROMPT_COMMAND;
#shopt -u promptvars

#export PS1;

PS2="\[${yellow}\]- \[${reset}\]";
export PS2;
