#!/usr/bin/env bash

# Prompt style most of the code grabed from https://github.com/mathiasbynens/dotfiles
# Colors adjusted to Gruvbox color pallete https://github.com/morhetz/gruvbox-contrib/blob/master/color.table

if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	black=$(tput setaf 234);
	blue=$(tput setaf 109);
	cyan=$(tput setaf 72);
	green=$(tput setaf 64);
	orange=$(tput setaf 208);
	purple=$(tput setaf 175);
	red=$(tput setaf 167);
	violet=$(tput setaf 108);
	white=$(tput setaf 223);
	yellow=$(tput setaf 214);
else
	bold='';
	reset="\e[0m";
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	orange="\e[1;33m";
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
fi;

# Using stock git-prompt script which has been shiped with
# git source code

source $HOME/.bashrc.d/git-prompt

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${bold}${red}";
    promptChar="#";
else
	userStyle="${orange}";
    #promptChar="==〉";
    promptChar="$"
fi;

# Highlight the hostname when connected via SSH.
if [[ "${SSH_TTY}" ]]; then
	hostStyle="${bold}${red}";
else
	hostStyle="${yellow}";
fi;


GIT_PS1_SHOWDIRTYSTATE=1;
GIT_PS1_SHOWUNTRACKEDFILES=1;
GIT_PS1_SHOWCOLORHINTS=1;
GIT_PS1_SHWSTASHSTATE=1;
PROMPT_COMMAND='__git_ps1 \
"\[\033]0;\w\007\]\[${bold}\]\n\[${reset}\]\[${userStyle}\]\u \
\[${white}\]@ \[${hostStyle}\]\h \[${white}\]: \[${cyan}\]\w\
\[${reset}\]" "\n\[${white}\]$promptChar \[${reset}\]"';

export PROMPT_COMMAND;
#shopt -u promptvars
#PS1="\[\033]0;\w\007\]"; # working directory base name
#PS1+="\[${bold}\]\n\[${reset}\]";
#PS1+="\[${userStyle}\]\u ";
#PS1+="\[${white}\]@ ";
#PS1+="\[${hostStyle}\]\h ";
#PS1+="\[${white}\]: ";
#PS1+="\[${green}\]\w\[${reset}\]";
#PS1+='$(__git_ps1 "" "")';
#PS1+="\n";
#PS1+="\[${white}\]  $promptChar\[${reset}\]";
#export PS1;

PS2="\[${yellow}\]- \[${reset}\]";
export PS2;
